### ISSUE TITLE
Forward realtime binary data

### ISSUE THREAD

**Issue by nmaas87** [yamcs/python-yamcs-client#13]
Dear all,

I have a usecase where I need to provide the CCSDS data input into Yamcs to another tool siting behind Yamcs and having no possibility to access the raw stream directly (the Yamcs server instance is externally hosted and we get only access to the normal port for using it via Web/FatClient/API).

As far as I saw, I could go down the route of using the archive retrieval example ( https://github.com/yamcs/python-yamcs-client/blob/master/yamcs-client/examples/archive_retrieval.py ) and just pull all data from the last seconds, check if I sent them to the tool or not and in the later case forward it via UDP/TCP.

However, this puts a lot of strain on the overall setup. Is there a possibility to expand the asynchronous parameter subscription (which is already available) to an asynchronous subscription to the overall, raw CCSDS packet?

Thanks a lot :)

Nico

**Comment by fqqb** [comment]
On master, and released as of 1.6.6
https://github.com/yamcs/python-yamcs-client/releases/tag/client-1.6.6

See here for an example:
https://docs.yamcs.org/python-yamcs-client/examples/packet_subscription/
