### ISSUE TITLE
It would be good to support requests.Session() verify='/path/to/certfile' option

### ISSUE THREAD

**Issue by AdamElliott-AB** [yamcs/python-yamcs-client#14]
The requests library has an option to specify the location of a custom certificate to use when doing certificate verification. This library however only allows tls_verify to be True or False. We can use the REQUESTS_CA_BUNDLE environment variable for this purpose but supporting having a tls_verify='/path/to/certfile' option would be preferred.

https://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification

https://github.com/yamcs/python-yamcs-client/blob/dec6bb3dab26aeb520e7f43e8406bf7928fcb084/yamcs-client/src/yamcs/core/context.py#L20

https://github.com/yamcs/python-yamcs-client/blob/dec6bb3dab26aeb520e7f43e8406bf7928fcb084/yamcs-client/src/yamcs/core/context.py#L41

**Comment by fqqb** [comment]
On master, and included in latest release.

**Comment by AdamElliott-AB** [comment]
Wonderful! Thank you.
