### ISSUE TITLE
Multi-parameter extraction

### ISSUE THREAD

**Issue by nmaas87** [yamcs/python-yamcs-client#15]
Dear all,
with ````list_parameter_values```` it is possible to extract data from a single TM/parameter for a given period of time.
Could you expand this possibilty to allow for a list of parameters to be given into the function which are then extracted at the same time and shown side by side to allow for complete extractions of an experiment cycle?

Thanks a lot,

Nico

**Comment by fqqb** [comment]
On master, and in latest release.

There's a new method ``stream_parameter_values`` available on an archive client.
The method returns an iterable of ParameterData objects (https://docs.yamcs.org/python-yamcs-client/tmtc/model/#yamcs.tmtc.model.ParameterData), one such object for each chronological unique generation time.
