### ISSUE TITLE
Cannot set a double-precision parameter without loss of significant digits

### ISSUE THREAD

**Issue by merose** [yamcs/python-yamcs-client#16]
The Python `set_parameter_value` API call converts all floating point values to a single-precision floating-point _Value_ type in the HTTP API payload. You can see that `set_parameter_value` uses `_build_value_proto` to create the value on line 626 (https://github.com/yamcs/python-yamcs-client/blob/master/yamcs-client/src/yamcs/tmtc/client.py#L626):

    req = _build_value_proto(value)

And `_build_value_proto` does not have any way of creating a double-precision floating-point value, only FLOAT type:

    def _build_value_proto(value):
        proto = yamcs_pb2.Value()
        if isinstance(value, bool):
            proto.type = proto.BOOLEAN
            proto.booleanValue = value
        elif isinstance(value, float):
            proto.type = proto.FLOAT
            proto.floatValue = value
        elif isinstance(value, int) and value > 2147483647:
    ...

There needs to be a way to write double-precision floating-point values using the complete double precision.

To reproduce:

1. Create a _local_ parameter of a 64-bit floating-point type.
2. Write the value 123.4 to the parameter using the Python `set_parameter_value` API.

Expected result: Viewing the value in the Yamcs UI shows a value of  123.4000000000000

Actual result: The value shows int the Yamcs web UI as 123.4000015258789

**Comment by fqqb** [comment]
Thanks. Changed to double, matching with Python.
