### ISSUE TITLE
Protobuf Issue

### ISSUE THREAD

**Issue by nmaas87** [yamcs/python-yamcs-client#22]
Dear all,
I think there is an issue with the requirements for python-yamcs-client:

https://github.com/yamcs/python-yamcs-client/blob/d22f06fe64bd335b1a8bd821b4c212111d127d63/yamcs-client/setup.py#L41

The current protobuf history cannot satisfy these requirements, there is no version "protobuf>=3.8,<4" - only 3.20.3 and then some 4.0.0rc versions and up...

https://pypi.org/project/protobuf/#history

**Comment by fqqb** [comment]
but 3.20.3 matches that specification doesn't it?
are you getting a specific error? Maybe some conflict with another dependency?

**Comment by nmaas87** [comment]
Yeah, pip3 gave me following error, while trying to install if offline on another machine:
````  
Could not find a version that satisfies the requirement protobuf<4,>=3.8 (from yamcs_client->-r requirements.txt (line 1)) (from versions: )
No matching distribution found for protobuf<4,>=3.8 (from yamcs_client->-r requirements.txt (line 1))
````

You're right, I mixed up the versioning schema, so it turned out that the machine I downloaded the pip packages with was a Debian 11 with python 3.9 - and the one I tried to play the packages back was a Debian 10 with python 3.7 - so what happend was that it had downloaded the ````protobuf-3.20.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl```` wheel which did not install on the offline machine - and hence the error came up.

I got around it by creating a own download for the protobuf repo and forced it to use python 3.7.x as target system:
````
requirements_protobuf.txt
protobuf==3.20.3

pip3 download --python-version "37" --only-binary=:all: -r requirements_protobuf.txt
````

Then i offline installed protobuf before all the rest
````
pip3 install --no-index --find-links ./ -r requirements_protobuf.txt
````

... and with that the error was gone and the yamcs python api successfully installed.

Sorry for the confusion! :)
