### ISSUE TITLE
Websocket error when calling `create_parameter_subscription`

### ISSUE THREAD

**Issue by keck-in-space** [yamcs/python-yamcs-client#23]
Hello, I am getting the following error when I attempt to subscribe to parameters.

```sh
 ERROR: WebSocket error: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
```

Can you help me determine the cause of this issue? I am running yamcs-client v.1.8.8.

**Comment by fqqb** [comment]
Not sure, error does not come from this library directly.

Two thoughts:
* Try to see if the error is also there with another method (for example, [get_parameter_value](https://docs.yamcs.org/python-yamcs-client/tmtc/client/#yamcs.tmtc.client.ProcessorClient.get_parameter_value)) -- this to determine whether the error is specific to WebSocket.
* Check if there's any proxy between the client and the server. Proxies may cause problem with WebSocket.

**Comment by keck-in-space** [comment]
Thanks for the tips. `get_parameter_value` fails due to a connection timeout. I'll work with our sysadmin to check out the server config. I appreciate the help.

**Comment by keck-in-space** [comment]
Thanks for the help. This did appear to be a network config issue.
