### ISSUE TITLE
Python API needs to have realtime stream subscription added to match functionality of HTTP API

### ISSUE THREAD

**Issue by trgarvey** [yamcs/python-yamcs-client#4]
The HTTP API functionality for subscribing to realtime streams should be extended to the Python API.  User authenticated permissions (i.e. stream viewing) should also be obeyed by the API.

**Comment by fqqb** [comment]
Closing. Stream subscription has been there for a long time already:
https://docs.yamcs.org/python-yamcs-client/archive/client/#yamcs.archive.client.ArchiveClient.create_stream_subscription

Enforcement of privileges is server-side. I'm not aware of problems related to that in combination with stream subscription.
