### ISSUE TITLE
SoftwareParameterManager not activated for this processor

### ISSUE THREAD

**Issue by nmaas87** [yamcs/python-yamcs-client#9]
Hi,

I tried to write some parameters for the first time with the python-yamcs-client.
Cached reading works without problems, but writing, i.e. with

````processor.set_parameter_value('/JPL/MARS2060/err', 1)````

gives the following exception:

````yamcs.core.exceptions.YamcsError: 400 Client Error: SoftwareParameterManager not activated for this processor````

I am currently trying to build the documentation within this repo to read up on this, probably my fault for doing some error in the configuration :)

**Comment by fqqb** [comment]
The client is correctly telling you that you're trying to update a parameter which is not updatable.
The reason being that your server is not setup for it.

It looks like you're missing the LocalParameterManager in your configuration. Refer to here:
https://github.com/yamcs/yamcs/blob/c6679c7fb62ecedc7af909720db161372017bae2/examples/simulation/src/main/yamcs/etc/processor.yaml#L16

But the source of your parameter will also need to be set such that Yamcs will allow writing to it, you cannot just write to a telemetry parameter for example, that's protected from user updates. In the 'simulation' example from the Yamcs source code the /YSS/SIMULATOR/AllowCriticalTC1 and /YSS/SIMULATOR/AllowCriticalTC2 are two examples of writeable parameters.

(btw: we have online docs: https://yamcs.org/docs/python-yamcs-client/)

**Comment by nmaas87** [comment]
Thank you very much, that was a perfect answer.
I had the LocalParameterManager configured / in the YAML file, however,
I did setup the parameters in my MDB in the "Parameters" section, like normal TM parameters.
However, as you pointed out correctly, they need to go to the "LocalParameters" section to be "writeable".
Also the MDB view in the Webserver does point them out as Source "Local" now - instead of Telemetered - and with that, it does work 👍🏻
